### ISSUE TITLE
DBs question

### ISSUE THREAD

**Issue by SargeroDeV** [EyalMK/Draenor-Core#1]
Hello, could you provide a link with the complete dbs, because in the repo are the sqls a bit disorganized and the auth db is missing.

**Comment by EyalMK** [comment]
Hey,
I have the auth sql from back in the day. Found it in a private repo - https://pastebin.com/Mf0Tftja
If you want to run all the SQLs at once, use - https://github.com/EyalMK/Draenor-Core/blob/master/sql/updates/sql%20compiler.BAT
It'll compile all the SQLs in the folder into a single SQL file which you can run in the DB.
I'd appreciate if you forked the repo :)

**Comment by SargeroDeV** [comment]
Hello, you are very kind, I am working on a MoP core for a server that is in beta phase, for when the server becomes official keep it being public-source and try to encourage the development of more modern wow expansions to 335, browsing I found this source of yours, which is undoubtedly the best WoD that is currently public and my idea would be in the not too distant future to make an open-source project with this WoD, if you can upload the missing dbs, since the characters, the hotfixes and the web are also missing, and if it is not too much trouble the updated world, thank you very much for deciding to publish the source.

**Comment by EyalMK** [comment]
I wish I could be of further assistance, but we deleted the characters DB to protect our old players' privacy
I remember we deprecated the web DB since we had no use for it back then.
I have no idea why the hotfix wasn't uploaded.
I suggest you try using Firestorm's DB for characters, hotfix and web. Apply the SQLs we have for characters, I'm pretty sure Tele made them to save raid progression.
As long as you work with our worldlive DB, you should be good to commit all the SQLs we have saved. I'm fairly certain I've used GUIDs a lot to fix waypoints.

Good luck on your project and way to go with the open sourcing! We should all be benefiting, learning and contributing to each other.
